"use client"

import { useState } from "react"
import {
    Download,
    FileText,
    BarChart3,
    Users,
    Upload,
    DollarSign,
    Activity,
    Calendar,
    Loader,
    Eye,
    X,
} from "lucide-react"

interface ReportData {
    type: string
    startDate: Date
    endDate: Date
    generatedAt: Date
    generatedBy: string
    data: any[]
    summary?: any
}

const REPORT_TYPES = [
    { id: "users", name: "Users Report", icon: Users, description: "New users and activity" },
    { id: "uploads", name: "Uploads Report", icon: Upload, description: "File uploads and transfers" },
    { id: "revenue", name: "Revenue Report", icon: DollarSign, description: "Payments and subscriptions" },
    { id: "portals", name: "Portals Report", icon: FileText, description: "Portal usage and stats" },
    { id: "activity", name: "Activity Log", icon: Activity, description: "System activity and logs" },
]

export default function ReportsClient() {
    const [selectedType, setSelectedType] = useState<string | null>(null)
    const [startDate, setStartDate] = useState("")
    const [endDate, setEndDate] = useState("")
    const [reportData, setReportData] = useState<ReportData | null>(null)
    const [loading, setLoading] = useState(false)
    const [showPreview, setShowPreview] = useState(false)

    const getDateRangeDefaults = () => {
        const end = new Date()
        const start = new Date()
        start.setDate(start.getDate() - 30)

        return {
            startDate: start.toISOString().split("T")[0],
            endDate: end.toISOString().split("T")[0]
        }
    }

    const defaults = getDateRangeDefaults()

    const handleGenerateReport = async () => {
        if (!selectedType || !startDate || !endDate) {
            alert("Please select a report type and date range")
            return
        }

        if (new Date(startDate) > new Date(endDate)) {
            alert("Start date must be before end date")
            return
        }

        setLoading(true)
        try {
            const res = await fetch("/api/admin/reports/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    type: selectedType,
                    startDate,
                    endDate
                })
            })

            if (res.ok) {
                const data = await res.json()
                setReportData(data)
                setShowPreview(true)
            }
        } catch (error) {
            console.error("Failed to generate report:", error)
            alert("Failed to generate report")
        } finally {
            setLoading(false)
        }
    }

    const exportToCSV = () => {
        if (!reportData) return

        let csv = ""
        const reportType = REPORT_TYPES.find(t => t.id === reportData.type)

        // Header
        csv += `Report: ${reportType?.name}\n`
        csv += `Generated: ${new Date(reportData.generatedAt).toLocaleString()}\n`
        csv += `Period: ${new Date(reportData.startDate).toLocaleDateString()} - ${new Date(reportData.endDate).toLocaleDateString()}\n`
        csv += `Generated By: ${reportData.generatedBy}\n\n`

        if (reportData.summary) {
            csv += "Summary\n"
            Object.entries(reportData.summary).forEach(([key, value]) => {
                csv += `${key},${value}\n`
            })
            csv += "\n"
        }

        // Data headers
        if (reportData.data.length > 0) {
            const keys = Object.keys(reportData.data[0])
            csv += keys.join(",") + "\n"

            // Data rows
            reportData.data.forEach(row => {
                const values = keys.map(key => {
                    let value = row[key]
                    if (typeof value === "object") {
                        return JSON.stringify(value).replace(/,/g, ";")
                    }
                    return String(value).replace(/,/g, ";")
                })
                csv += values.join(",") + "\n"
            })
        }

        // Download
        const blob = new Blob([csv], { type: "text/csv" })
        const url = window.URL.createObjectURL(blob)
        const a = document.createElement("a")
        a.href = url
        a.download = `report-${reportData.type}-${Date.now()}.csv`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        window.URL.revokeObjectURL(url)
    }

    return (
        <div className="p-8">
            <div className="mb-8">
                <h1 className="text-3xl font-bold text-slate-900">Reports</h1>
                <p className="text-slate-600 mt-1">Generate and manage admin reports</p>
            </div>

            {/* Report Types Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 mb-8">
                {REPORT_TYPES.map(type => {
                    const Icon = type.icon
                    return (
                        <button
                            key={type.id}
                            onClick={() => setSelectedType(type.id)}
                            className={`p-4 rounded-xl border-2 transition-all text-left ${selectedType === type.id
                                ? "border-slate-900 bg-slate-900 text-white"
                                : "border-slate-200 bg-white text-slate-900 hover:border-slate-900"
                                }`}
                        >
                            <div className="flex items-center gap-2 mb-2">
                                <Icon className="w-5 h-5" />
                                <p className="font-semibold">{type.name}</p>
                            </div>
                            <p className={`text-sm ${selectedType === type.id ? "text-slate-100" : "text-slate-600"}`}>
                                {type.description}
                            </p>
                        </button>
                    )
                })}
            </div>

            {/* Date Range Selection */}
            {selectedType && (
                <div className="bg-white rounded-xl border border-slate-200 p-6 mb-8">
                    <h3 className="text-lg font-bold text-slate-900 mb-4">Select Date Range</h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div>
                            <label className="block text-sm font-medium text-slate-900 mb-2">Start Date</label>
                            <input
                                type="date"
                                value={startDate || defaults.startDate}
                                onChange={(e) => setStartDate(e.target.value)}
                                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-slate-900 mb-2">End Date</label>
                            <input
                                type="date"
                                value={endDate || defaults.endDate}
                                onChange={(e) => setEndDate(e.target.value)}
                                className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-slate-900"
                            />
                        </div>
                        <div className="flex items-end">
                            <button
                                onClick={handleGenerateReport}
                                disabled={loading}
                                className="w-full px-4 py-2 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                            >
                                {loading ? (
                                    <>
                                        <Loader className="w-4 h-4 animate-spin" />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        <FileText className="w-4 h-4" />
                                        Generate Report
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Report Preview Modal */}
            {showPreview && reportData && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                    <div className="bg-white rounded-xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
                        {/* Header */}
                        <div className="flex items-center justify-between p-6 border-b border-slate-200 sticky top-0 bg-white">
                            <div>
                                <h2 className="text-2xl font-bold text-slate-900">
                                    {REPORT_TYPES.find(t => t.id === reportData.type)?.name}
                                </h2>
                                <p className="text-sm text-slate-500 mt-1">
                                    {new Date(reportData.startDate).toLocaleDateString()} - {new Date(reportData.endDate).toLocaleDateString()}
                                </p>
                            </div>
                            <button
                                onClick={() => setShowPreview(false)}
                                className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
                            >
                                <X className="w-5 h-5" />
                            </button>
                        </div>

                        <div className="p-6 space-y-6">
                            {/* Meta Info */}
                            <div className="grid grid-cols-2 gap-4">
                                <div className="bg-slate-50 p-4 rounded-lg">
                                    <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Generated</p>
                                    <p className="font-medium text-slate-900">
                                        {new Date(reportData.generatedAt).toLocaleString()}
                                    </p>
                                </div>
                                <div className="bg-slate-50 p-4 rounded-lg">
                                    <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">By</p>
                                    <p className="font-medium text-slate-900">{reportData.generatedBy}</p>
                                </div>
                            </div>

                            {/* Summary */}
                            {reportData.summary && (
                                <div>
                                    <h3 className="font-bold text-slate-900 mb-3">Summary</h3>
                                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                        {Object.entries(reportData.summary).map(([key, value]) => (
                                            <div key={key} className="bg-slate-50 p-4 rounded-lg">
                                                <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">
                                                    {key.replace(/([A-Z])/g, " $1").trim()}
                                                </p>
                                                <p className="font-bold text-slate-900">
                                                    {typeof value === "number" ? value.toFixed(2) : String(value)}
                                                </p>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            )}

                            {/* Data Table */}
                            {reportData.data.length > 0 && (
                                <div>
                                    <h3 className="font-bold text-slate-900 mb-3">
                                        Records ({reportData.data.length})
                                    </h3>
                                    <div className="overflow-x-auto">
                                        <table className="w-full text-sm">
                                            <thead className="bg-slate-50 border-b border-slate-200">
                                                <tr>
                                                    {Object.keys(reportData.data[0]).slice(0, 8).map(key => (
                                                        <th
                                                            key={key}
                                                            className="px-4 py-3 text-left font-semibold text-slate-900"
                                                        >
                                                            {key}
                                                        </th>
                                                    ))}
                                                </tr>
                                            </thead>
                                            <tbody className="divide-y divide-slate-200">
                                                {reportData.data.slice(0, 50).map((row, idx) => (
                                                    <tr key={idx} className="hover:bg-slate-50">
                                                        {Object.entries(row)
                                                            .slice(0, 8)
                                                            .map(([key, value]: [string, any], colIdx) => (
                                                                <td key={colIdx} className="px-4 py-3 text-slate-600">
                                                                    {typeof value === "object"
                                                                        ? JSON.stringify(value)
                                                                        : String(value).substring(0, 50)}
                                                                </td>
                                                            ))}
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                    {reportData.data.length > 50 && (
                                        <p className="text-xs text-slate-500 mt-3">
                                            Showing 50 of {reportData.data.length} records (view all in exported file)
                                        </p>
                                    )}
                                </div>
                            )}

                            {reportData.data.length === 0 && (
                                <div className="text-center py-12">
                                    <p className="text-slate-500">No data found for the selected date range</p>
                                </div>
                            )}

                            {/* Actions */}
                            <div className="flex gap-3 pt-4 border-t border-slate-200">
                                <button
                                    onClick={() => setShowPreview(false)}
                                    className="flex-1 py-2 px-4 border border-slate-200 text-slate-900 rounded-lg hover:bg-slate-50 transition-colors font-medium"
                                >
                                    Close
                                </button>
                                <button
                                    onClick={exportToCSV}
                                    className="flex-1 flex items-center justify-center gap-2 py-2 px-4 bg-slate-900 text-white rounded-lg hover:bg-slate-800 transition-colors font-medium"
                                >
                                    <Download className="w-4 h-4" />
                                    Export as CSV
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Empty State */}
            {!selectedType && (
                <div className="bg-white rounded-xl border border-slate-200 p-12 text-center">
                    <FileText className="w-12 h-12 text-slate-400 mx-auto mb-4" />
                    <h3 className="text-lg font-bold text-slate-900 mb-2">No Report Selected</h3>
                    <p className="text-slate-600">Select a report type above to get started</p>
                </div>
            )}
        </div>
    )
}
